import type { Config } from 'tailwindcss';
import daisyui from 'daisyui';
import typography from '@tailwindcss/typography';
import catppuccin from '@catppuccin/tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      // 8pt 网格间距
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      // 圆角规范
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
      },
    },
  },
  plugins: [
    typography,
    catppuccin({
      prefix: 'ctp',
      defaultFlavour: 'mocha',
    }),
    daisyui,
  ],
  // daisyUI 配置
  daisyui: {
    themes: [
      // 基础主题
      'light',
      'dark',

      // 氛围主题
      'cyberpunk',
      'synthwave',
      'retro',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',

      // 自定义主题
      {
        tech: {
          'primary': '#2563eb',
          'primary-content': '#ffffff',
          'secondary': '#f5f5f5',
          'secondary-content': '#171717',
          'accent': '#06b6d4',
          'accent-content': '#ffffff',
          'neutral': '#737373',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f5f5f5',
          'base-300': '#e5e5e5',
          'base-content': '#171717',
          'info': '#3b82f6',
          'success': '#22c55e',
          'warning': '#eab308',
          'error': '#ef4444',
          '--rounded-btn': '8px',
          '--rounded-box': '12px',
        },
      },
      {
        warm: {
          'primary': '#f97316',
          'primary-content': '#ffffff',
          'secondary': '#fff7ed',
          'secondary-content': '#7c2d12',
          'accent': '#facc15',
          'accent-content': '#422006',
          'neutral': '#78716c',
          'neutral-content': '#ffffff',
          'base-100': '#fffbf5',
          'base-200': '#fff7ed',
          'base-300': '#ffedd5',
          'base-content': '#422006',
          'info': '#3b82f6',
          'success': '#22c55e',
          'warning': '#eab308',
          'error': '#ef4444',
          '--rounded-btn': '12px',
          '--rounded-box': '16px',
        },
      },
      {
        elegant: {
          'primary': '#171717',
          'primary-content': '#ffffff',
          'secondary': '#d4af37',
          'secondary-content': '#171717',
          'accent': '#d4af37',
          'accent-content': '#171717',
          'neutral': '#525252',
          'neutral-content': '#ffffff',
          'base-100': '#faf9f7',
          'base-200': '#f5f5f4',
          'base-300': '#e7e5e4',
          'base-content': '#171717',
          'info': '#3b82f6',
          'success': '#16a34a',
          'warning': '#ca8a04',
          'error': '#dc2626',
          '--rounded-btn': '0px',
          '--rounded-box': '0px',
        },
      },
      {
        fresh: {
          'primary': '#16a34a',
          'primary-content': '#ffffff',
          'secondary': '#f0fdf4',
          'secondary-content': '#14532d',
          'accent': '#4ade80',
          'accent-content': '#14532d',
          'neutral': '#525252',
          'neutral-content': '#ffffff',
          'base-100': '#f8fdf8',
          'base-200': '#f0fdf4',
          'base-300': '#dcfce7',
          'base-content': '#14532d',
          'info': '#3b82f6',
          'success': '#22c55e',
          'warning': '#eab308',
          'error': '#ef4444',
          '--rounded-btn': '12px',
          '--rounded-box': '16px',
        },
      },
      {
        trustworthy: {
          'primary': '#1e40af',
          'primary-content': '#ffffff',
          'secondary': '#eff6ff',
          'secondary-content': '#1e3a8a',
          'accent': '#dbeafe',
          'accent-content': '#1e3a8a',
          'neutral': '#525252',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f8fafc',
          'base-300': '#f1f5f9',
          'base-content': '#171717',
          'info': '#3b82f6',
          'success': '#16a34a',
          'warning': '#ca8a04',
          'error': '#dc2626',
          '--rounded-btn': '4px',
          '--rounded-box': '8px',
        },
      },
      {
        playful: {
          'primary': '#a855f7',
          'primary-content': '#ffffff',
          'secondary': '#f472b6',
          'secondary-content': '#ffffff',
          'accent': '#facc15',
          'accent-content': '#581c87',
          'neutral': '#6b21a8',
          'neutral-content': '#ffffff',
          'base-100': '#fefcff',
          'base-200': '#faf5ff',
          'base-300': '#f3e8ff',
          'base-content': '#581c87',
          'info': '#3b82f6',
          'success': '#4ade80',
          'warning': '#facc15',
          'error': '#f87171',
          '--rounded-btn': '16px',
          '--rounded-box': '20px',
        },
      },
      {
        brutalist: {
          'primary': '#000000',
          'primary-content': '#ffffff',
          'secondary': '#ffffff',
          'secondary-content': '#000000',
          'accent': '#fde047',
          'accent-content': '#000000',
          'neutral': '#404040',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f5f5f5',
          'base-300': '#e5e5e5',
          'base-content': '#000000',
          'info': '#3b82f6',
          'success': '#16a34a',
          'warning': '#eab308',
          'error': '#dc2626',
          '--rounded-btn': '0px',
          '--rounded-box': '0px',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
} as Config;

export default config;
